;Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

(defn fib-seq
  ([]
    (fib-seq 1 2))
  ([nr1 nr2]
    (lazy-seq (cons nr1 (fib-seq nr2 (+ nr1 nr2))))))

(def fib-list (fib-seq))

(println (reduce
  (fn
    [sum nr]
    (if (= (mod nr 2) 0)
      (+ sum nr)
      sum))
  0
  (take-while #(< % 4000001) fib-list)))
