;The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
;1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
;Let us list the factors of the first seven triangle numbers:
; 1: 1
; 3: 1,3
; 6: 1,2,3,6
;10: 1,2,5,10
;15: 1,3,5,15
;21: 1,3,7,21
;28: 1,2,4,7,14,28
;36: 1,2,3,4,6,9,12,18,36
;45: 1,3,5,9,15,45
;We can see that 28 is the first triangle number to have over five divisors.
;What is the value of the first triangle number to have over five hundred divisors?

(def min-factors 500)

(defn nth-tri-number
  [n]
  (/ (* n (inc n)) 2))

(defn cnt-factors
  [nr]
  (loop [i 1
         k []]
    (let [r (rem nr i)]
      (cond
        (= nr 1) 1
        (some #(= % i) k) (count (distinct k))
        (= 0 r) (recur
          (inc i)
          (concat k [i (/ nr i)]))
        true (recur (inc i) k)))))

(println
  (loop [nth-tri 1]
    (when (= 0 (mod nth-tri 100))
      (println nth-tri (nth-tri-number nth-tri)))
    (let [tri-nr (nth-tri-number nth-tri)
          cnt (cnt-factors tri-nr)]
      (if (>= cnt min-factors)
        tri-nr
        (recur (inc nth-tri))))))

